###
###
### SCRIPT TO READ IN UM, IFS, and UM-CASIM model data
###
###

from __future__ import print_function
import time
import datetime
import numpy as np
import pandas as pd
from netCDF4 import Dataset
import numpy as np
import cartopy.crs as ccrs
import iris
import matplotlib.pyplot as plt
import matplotlib.cm as mpl_cm
import os
import seaborn as sns

#### import python functions
import sys
sys.path.insert(1, '../py_functions/')
from time_functions import calcTime_Mat2DOY, calcTime_Date2DOY
from readMAT import readMatlabStruct, readMatlabData
from physFuncts import calcThetaE, calcThetaVL
from pyFixes import py3_FixNPLoad

def quicklooksSonde(sonde):

    '''
    Notes from Tom's readme:
    Each sounding is in the Xdate_time_EDT variables. The data is organized such that column 7
    is the altitude, 3 is temperature, 4 is relative humidity, 10 is specific humidity, 12 is
    wind speed, and the rest you can probably figure out by looking at the variables. Some of
    them makes no sense at all; this is a quick monitiring file generated by the sounding
    system.

    There is also a variable named "sond" which is interpolated to same heights (in height). In
    that is also 13=potential temperature and 14=equivalent potential temperature. Time is the
    nominal times (00, 06, 12 etc UTC). The actual times are in the log file.
    '''

    SMALL_SIZE = 12
    MED_SIZE = 14
    LARGE_SIZE = 16

    plt.rc('font',size=MED_SIZE)
    plt.rc('axes',titlesize=MED_SIZE)
    plt.rc('axes',labelsize=MED_SIZE)
    plt.rc('xtick',labelsize=MED_SIZE)
    plt.rc('ytick',labelsize=MED_SIZE)
    plt.figure(figsize=(12,5))
    plt.rc('legend',fontsize=MED_SIZE)
    plt.subplots_adjust(top = 0.9, bottom = 0.12, right = 0.9, left = 0.12,
            hspace = 0.22, wspace = 0.4)

    plt.subplot(131)
    plt.plot(sonde[:,2], sonde[:,6])
    plt.ylabel('Z [m]')
    plt.xlabel('Temperature [K]')
    plt.ylim([0,1e4])

    plt.subplot(132)
    plt.plot(sonde[:,9], sonde[:,6])
    plt.xlabel('Spec. Hum. [g/kg]')
    plt.ylim([0,1e4])

    plt.subplot(133)
    plt.plot(sonde[:,3], sonde[:,6])
    plt.xlabel('Rel. Hum. [%]')
    plt.ylim([0,1e4])

    plt.show()


def main():

    START_TIME = time.time()
    print ('******')
    print ('')
    print ('Start: ' + time.strftime("%c"))
    print ('')

    '''
    Python script to build initialisation data for MONC from radiosondes
    '''

    print ('Import ASCOS radiosonde data:')
    print ('...')

    print ('Load radiosonde data from Jutta...')
    sondes = readMatlabData('../DATA/radiosondes.mat')

    print ('')
    print (sondes.keys())

    ## -------------------------------------------------------------
    ## Load radiosonde from 20180827 1200UTC (as in Tom's work)
    ## -------------------------------------------------------------
    sonde = sondes['X080827_12_EDT']

    ## -------------------------------------------------------------
    ## Quicklook plots of chosen sonde
    ## -------------------------------------------------------------
    figure = quicklooksSonde(sonde)

    # -------------------------------------------------------------
    # FIN.
    # -------------------------------------------------------------
    END_TIME = time.time()
    print ('******')
    print ('')
    print ('End: ' + time.strftime("%c"))
    print ('')


if __name__ == '__main__':

    main()
