#!/bin/bash --login
#PBS -N MONC
#PBS -l select=1
#PBS -l walltime=02:45:00
#PBS -j oe
#PBS -P monc
#PBS -q normal

echo Starting job

# Make sure any symbolic links are resolved to absolute path
export PBS_O_WORKDIR=$(readlink -f $PBS_O_WORKDIR)

# Change to the direcotry that the job was submitted from
cd $PBS_O_WORKDIR

# Set the number of threads to 1
#   This prevents any system libraries from automatically  
#   using threading.
export OMP_NUM_THREADS=1

# set env variables for submission command
config_path=config_filepath
checkpoint_fn="output_file"

aprun -n np ./build/bin/monc_driver.exe --config=$config_path  --checkpoint_file=$checkpoint_fn &> out2
