name: ARC4 compile and run

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ARC4

    steps:
    - uses: actions/checkout@v2
