name: github pages

on:
  push:
    branches:
      - doxygen-action  # Set a branch name to trigger deployment

jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Build
        uses: mattnotmitt/doxygen-action@v1
        with:
          doxyfile-path: './doc/Doxyfile'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Default Doxyfile build documentation to html directory. 
          # Change the directory if changes in Doxyfile
          publish_dir: ./html
