#!/bin/bash --login
#PBS -N MONC
#PBS -l select=1
#PBS -l walltime=00:45:00
#PBS -j oe
#PBS -P monc
#PBS -q normal

# Make sure any symbolic links are resolved to absolute path 
export PBS_O_WORKDIR=$(readlink -f $PBS_O_WORKDIR)

# Change to the direcotry that the job was submitted from 
cd $PBS_O_WORKDIR

export SUBMISSION_SCRIPT_NAME=debug_configs/submonc_fire_sc_casim_3
export MONC_EXEC=./build/bin/monc_driver.exe

export TESTCASE=debug_configs/fire_sc_casim_3.mcf
export STDOUT_DIR=debug_configs/
export CP_DIR=debug_configs/
export RUN_NAME=fire_sc_casim_3_
export NPES=3
export MAX_CONTINUATION_RUNS=20

ulimit -c unlimited

. test_suite/checkpoint_test_suite/continuation.sh

run_monc

